[package]
name = "ffmpeg"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#[[bin]]
#name = "ffmpeg"
#path = "src/lib.rs"

[dependencies]

[build-dependencies]
bindgen = "0.65.1"